name: CI Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Run prek checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Rust toolchain
        run: echo "RUST_TOOLCHAIN=$(make print-rust-toolchain)" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy

      - name: Run prek
        uses: j178/prek-action@v2
        with:
          extra-args: "--all-files"

  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Rust toolchain
        run: echo "RUST_TOOLCHAIN=$(make print-rust-toolchain)" >> "$GITHUB_ENV"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends nasm grub-common grub-pc-bin xorriso mtools

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rust-src

      - name: Build Kernel iso
        run: make iso

      - name: Upload ISO artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: zkrnl32-${{ github.sha }}.iso
          path: build/zkrnl32.iso
          if-no-files-found: error
          compression-level: 0
          archive: false
